CREATE DATABASE sis;
USE sis;
CREATE TABLE IF NOT EXISTS student (
	id BIGINT NOT NULL AUTO_INCREMENT,
	last_name VARCHAR(255) NOT NULL,
	first_name VARCHAR(255) NOT NULL,
	middle_name VARCHAR(255) NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT pk_student_id PRIMARY KEY(id)
);